import os
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

MONGO_URI= os.getenv("MONGODB_URL")
DB_NAME = "test"
COLLECTION_NAME = "characters"

initial_characters = [
    {
        "CHARACTER": "Annabelle",
        "SOURCE": "The Conjuring Universe (Fictional) / Ed & Lorraine Warren Case Files (Real)",
        "IS_PART_OF_SERIES": "Yes",
        "GENDER_DESCRIPTION": "Female doll, vessel for a demonic entity",
        "IS_MALE": "No",
        "IS_FEMALE": "Yes",
        "IS_HUMAN": "No (Inanimate object)",
        "IS_FICTIONAL": "No (its haunting is debated)",
        "PORTRAYED_BY": "N/A (Prop)",
        "ORIGIN_CINEMA": "American Horror",
        "ORIGIN_LANGUAGE": "English",
        "FILM_SETTING_REGION": "Los Angeles, CA; Monroe, CT (Warren's Museum)",
        "DOLL_TYPE_REAL": "Raggedy Doll (Cloth)",
        "DOLL_TYPE_FICTIONAL": "Porcelain Doll (Grotesque, antique)",
        "SUPERNATURAL_NATURE": "Demonic Conduit / Manifestation Point",
        "IS_CRIMINAL": "Yes (Responsible for property damage and bodily harm, allegedly)",
        "TARGET_ITEM": "Human Soul",
        "PRIMARY_MOTIVATION": "The demon's goal is to gain permission to enter and possess a human host.",
        "GOAL": "To cause fear, break down spiritual defenses, and escape its containment.",
        "HAS_SIGNATURE_PHRASE": "No (Communicates via notes like 'Help Us' in real-life claims)",
        "HAS_DISTINGUISHING_TRAIT": "Yes (Locked in a specially consecrated glass case with a cross)",
        "PRIMARY_COLORS": "White (Dress), Red (Hair/Ribbon), Brown (Wood case)", 
        "IS_A_HERO": "No",
        "IS_A_VILLAIN": "Yes (Primary antagonist)",
        "APPEARANCE_TRAITS": ["Fictional: Cracked porcelain and menacing expression.", "Real: Simple Raggedy Ann appearance (cloth, yarn hair)."],
        "BEHAVIOR_TRAITS": ["Teleportation", "Materialization (Creating hand-written notes)", "Manipulation (Pretends to be a harmless child's spirit)."],
        "RELATIONSHIPS": {"OWNERS_REAL": "Donna (Original); Ed and Lorraine Warren (Investigators)", "JAILERS": "Ed and Lorraine Warren"},
        "STATUS_AT_END_OF_FILM": "Relocked in the Warrens' artifact room, its containment is temporary but effective.",
        "HAS_SEQUEL_PLANNED": "Yes (Its presence continues to drive future *The Conjuring Universe* films)",
          "REAL_LIFE_OWNER_CLAIMED_1_ROLE": "Student Nurse",
  "REAL_LIFE_OWNER_CLAIMED_2_RELATION": "Roommate",
  "REAL_LIFE_ACQUISITION_CONTEXT": "Birthday gift from the mother of Owner 1",
  "REAL_LIFE_PURCHASE_LOCATION_TYPE": "Hobby Store (Bought second-hand)",
  "REAL_LIFE_DOLL_TYPE_TRUE": "Classic Raggedy Cloth Doll",
  "REAL_LIFE_DOLL_HAIR_MATERIAL": "Red Yarn",
  "REAL_LIFE_DOLL_PHYSICAL_FEATURE_1_SHAPE": "Triangular nose",
  "REAL_LIFE_DOLL_PHYSICAL_FEATURE_2_EXPRESSION": "Half-smile",
  "REAL_LIFE_DOLL_CLOTHING_1_STYLE": "Calico-pattern dress",
  "REAL_LIFE_DOLL_CLOTHING_2_ITEMS": "Striped stockings and undergarments",
  "REAL_LIFE_INITIAL_INCIDENT_DECADE": "1970s",
  "REAL_LIFE_APARTMENT_STATE": "Connecticut (Hartford area)",
  "REAL_LIFE_VICTIM_ATTACKED_RELATION": "Owner's friend (Lou)",
  "REAL_LIFE_PHYSICAL_ATTACK_WOUNDS": "Claw marks (on chest)",
  "REAL_LIFE_WOUND_HEALING_TIME": "Healed completely within 48 hours",
  "REAL_LIFE_PARCHMENT_NOTES_FOUND": "Yes (Materialization evidence)",
  "REAL_LIFE_NOTES_CONTENT_1_PLEA": "'Help Us'",
  "REAL_LIFE_NOTES_CONTENT_2_TARGET": "'Help Lou'",
  "REAL_LIFE_NOTES_WRITING_MEDIUM": "Pencil (Claimed by original owners)",
  "REAL_LIFE_BLOOD_APPEARANCE_LOCATION": "On the object's hands and chest",
  "REAL_LIFE_FIRST_INVESTIGATOR_TYPE": "Psychic Medium (Contacted by owners)",
  "REAL_LIFE_MEDIUM_SPIRIT_AGE_CLAIM": "7 years old (Allegedly benevolent spirit)",
  "REAL_LIFE_MEDIUM_SPIRIT_DEATH_CONTEXT": "Died in a field where the dwelling now stands",
  "REAL_LIFE_FAMOUS_INVESTIGATORS_TYPE": "Demonologists/Paranormal Researchers (The Warrens)",
  "REAL_LIFE_INVESTIGATORS_SPIRIT_TYPE_CONCLUSION": "Inhuman/Demonic Entity",
  "REAL_LIFE_INVESTIGATORS_OBJECT_STATUS": "Manipulated (Not possessed itself)",
  "REAL_LIFE_ENTITY_PRIMARY_GOAL": "Seeking human possession (The nurse's soul)",
  "REAL_LIFE_CLERGY_CONSULTED": "Episcopal Priest",
  "REAL_LIFE_CLERGY_ACCIDENT_RESULT": "Near-fatal car accident (After dismissing the threat)",
  "REAL_LIFE_LOCATION_CLEANSING_RITUAL": "Apartment Exorcism",
  "REAL_LIFE_TRANSPORT_SECURITY_MEASURE": "Avoiding major highways (Fear of vehicular sabotage)",
  "CONTAINMENT_LOCATION_FORMER_TYPE": "Occult Museum (In Connecticut)",
  "CONTAINMENT_LOCATION_CURRENT_STATUS": "Private collection/Part of a traveling exhibit",
  "CONTAINMENT_ENCLOSURE_TYPE": "Locked, sacred display case",
  "CONTAINMENT_ENCLOSURE_MATERIALS": "Wood and Plexiglass",
  "CONTAINMENT_ENCLOSURE_HOLY_INSCRIPTION_1": "Lord's Prayer",
  "CONTAINMENT_ENCLOSURE_HOLY_INSCRIPTION_2": "Saint Michael's Prayer",
  "CONTAINMENT_ENCLOSURE_WARNING_SIGN": "'Do Not Touch'",
  "INVESTIGATION_FAMOUS_START_DECADE": "Early 1970s",
  "PARANORMAL_ACTIVITY_TYPE_1": "Spontaneous Relocation (Teleportation across rooms)",
  "PARANORMAL_ACTIVITY_TYPE_2": "Posture Changes (Sitting, standing, kneeling)",
  "PARANORMAL_ACTIVITY_TYPE_3": "Brief Levitation (Observed by investigators post-collection)",
  "PARANORMAL_ACTIVITY_TYPE_4": "Localized Thermal Drop",
  "PARANORMAL_ACTIVITY_TYPE_5": "Nocturnal Percussion Sounds",
  "PARANORMAL_ACTIVITY_TYPE_6": "Electromagnetic Interference/Object destruction (Flickering lights/Exploding frames)",
  "CRITICAL_ASSESSMENT_STATUS": "Controversial/Dismissed as fabrication",
  "CRITICAL_ASSESSMENT_CATEGORY": "Modern Urban Legend",
  "CRITICAL_ASSESSMENT_INVESTIGATOR_DOUBT": "Warren claims often challenged by skeptics",
  "FICTIONAL_ADAPTATION_OBJECT_TYPE": "Creepy Porcelain Doll (In the films)",
  "FICTIONAL_ADAPTATION_DOLL_AESTHETICS_1": "Visually unsettling",
  "FICTIONAL_ADAPTATION_DOLL_AESTHETICS_2": "Menacing",
  "FICTIONAL_ADAPTATION_DEBUT_FILM": "The Conjuring (2013)",
  "FICTIONAL_ADAPTATION_DEBUT_CONTEXT": "Opening scene case file/Lecture",
  "FICTIONAL_ADAPTATION_OWNER_1_STATUS": "Pregnant Wife (Mia Form)",
  "FICTIONAL_ADAPTATION_OWNER_2_STATUS": "Doctor Husband (John Form)",
  "FICTIONAL_ADAPTATION_OWNER_3_NURSE_LINK": "Purchased by a mother for her nursing student daughter",
  "FICTIONAL_ADAPTATION_ORIGIN_SETTING_ERA": "Late 1960s",
  "FICTIONAL_ADAPTATION_ORIGIN_GEOGRAPHY": "Southern California",
  "FICTIONAL_ADAPTATION_ORIGIN_GROUP_NAME": "The Disciples of the Ram (Satanic Cult)",
  "FICTIONAL_ADAPTATION_ORIGIN_SCENE_CONTEXT": "Apartment invasion and ritualistic murder",
  "FICTIONAL_ADAPTATION_ORIGIN_CULT_MEMBER_DEATH_RITUAL": "Suicide while grasping the object",
  "FICTIONAL_ADAPTATION_DEMON_ENTRY_METHOD": "Blood dripping into the object's eye socket",
  "FICTIONAL_ADAPTATION_PREQUEL_1_TITLE": "Creation (2017)",
  "FICTIONAL_ADAPTATION_PREQUEL_1_SETTING_YEAR": "1955",
  "FICTIONAL_ADAPTATION_PREQUEL_1_SETTING_TYPE": "Dollmaker's isolated home/Orphanage",
  "FICTIONAL_ADAPTATION_PREQUEL_1_CREATOR_PROFESSION": "Dollmaker (Samuel Mullins)",
  "FICTIONAL_ADAPTATION_PREQUEL_1_GRIEF_MOTIVATION": "Grieving the loss of their 7-year-old daughter",
  "FICTIONAL_ADAPTATION_PREQUEL_1_GIRL_TRAGEDY_CAUSE": "Hit by a car",
  "FICTIONAL_ADAPTATION_PREQUEL_1_HOST_HUMAN": "Orphan girl named Janice (Possessed)",
  "FICTIONAL_ADAPTATION_PREQUEL_1_HOST_ADOPTION_FAMILY": "The Higgins family",
  "FICTIONAL_ADAPTATION_SEQUEL_1_TITLE": "Comes Home (2019)",
  "FICTIONAL_ADAPTATION_SEQUEL_1_SETTING_ERA": "Early 1970s (A year after the Warrens acquired it)",
  "FICTIONAL_ADAPTATION_SEQUEL_1_PLOT_DRIVER": "Accidentally released from its case",
  "FICTIONAL_ADAPTATION_SEQUEL_1_CHILD_PROTAGONIST": "The Investigators' young daughter (Judy Warren)",
  "CINEMATIC_UNIVERSE_INCLUSION_1": "The Conjuring 2 (2016)",
  "CINEMATIC_UNIVERSE_INCLUSION_2": "The Curse of La Llorona (2019)",
  "CINEMATIC_UNIVERSE_INCLUSION_3": "The Devil Made Me Do It (2021)",
  "CINEMATIC_UNIVERSE_INCLUSION_4": "Shazam! Fury of the Gods (2023) (Brief appearance)",
  "CINEMATIC_UNIVERSE_NAME_FULL": "The Conjuring Universe",
  "REAL_LIFE_DOLL_APPEARANCE_ADJECTIVE": "Plain-looking (as described by a reporter)",
  "REAL_LIFE_MOVEMENT_BEHAVIOR_1": "Rocking/Falling from furniture",
  "REAL_LIFE_MOVEMENT_BEHAVIOR_2": "Upright/Leaning against furniture",
  "REAL_LIFE_MOVEMENT_BEHAVIOR_3": "Postures it cannot naturally hold (e.g., kneeling)",
  "REAL_LIFE_APARTMENT_LAND_HISTORY": "Reportedly a former open field",
  "REAL_LIFE_INVESTIGATORS_CUSTODIAN": "The Warren Family Estate/NESPR",
  "REAL_LIFE_CURRENT_TOUR_NAME_CLAIM": "Devils on the Run",
  "REAL_LIFE_TOUR_INCIDENT_CONTEXT": "Handler death occurred during the tour",
  "REAL_LIFE_DISPLAY_STATUS": "Behind locked glass (When not on tour)",
  "REAL_LIFE_ENTITY_TRUE_NAME_STATUS": "Unknown (The demon never gave its true name)",
  "ENTITY_MANIPULATION_METHOD": "Pretending to be a ghost to exploit kindness",
  "OBJECT_CLASSIFICATION_INVESTIGATOR_TERM": "Non-possessable object (Used as a tool/conduit)"

    },
    {
        "CHARACTER": "Pennywise",
        "SOURCE": "It (1986) by Stephen King",
        "IS_PART_OF_SERIES": "Yes (Stephen King's Multiverse / It Films & Miniseries)",
        "GENDER_DESCRIPTION": "Genderless/Female (True form is a giant spider laying eggs) / Male (as Pennywise the Clown)",
        "IS_MALE": "Yes (Primary form)",
        "IS_HUMAN": "No (Ancient, trans-dimensional alien entity)",
        "IS_FICTIONAL": "Yes",
        "PORTRAYED_BY": "Tim Curry (1990), Bill Skarsgård (2017/2019)",
        "ORIGIN_LITERATURE": "American Horror Novel",
        "FILM_SETTING_REGION": "Derry, Maine, USA (Crashes down in the area as an asteroid)",
        "SUPERNATURAL_NATURE": "Cosmic/Eldritch Horror (Entity from the Macroverse/Todash Darkness)",
        "PRIMARY_MOTIVATION": "To feed on the fear of children (their fear 'salts the meat') and perpetuate its feeding/sleep cycle.",
        "GOAL": "To consume the children of Derry every 27 years before retreating to hibernation.",
        "CYCLICAL_ACTIVITY": "Wakes and feeds roughly every 27 years.",
        "POWERS": ["Shapeshifting", "Illusion & Mind Control", "Regeneration/Immortality", "The Deadlights"],
        "WEAKNESSES": ["Belief/Confidence", "Ritual of Chüd", "Friendship/Love"],
        "SIGNATURE_PHRASE": "You'll float too!",
        "NEMESIS": "The Losers' Club (Bill Denbrough is the primary leader)",
        "CREATOR_NOVEL": "The Other (An even older cosmic entity)",
        "STATUS_AT_END_OF_FILM": "Killed by The Losers' Club (its heart is crushed/it shrinks and is beaten).",
        "IS_A_VILLAIN": "Yes (Pure Evil)",
        "PRIMARY_CHOSEN_FORM": "Dancing Clown",
        "REAL_LIFE_AUTHOR_CREATOR": "Stephen King",
        "NOVEL_DEBUT_YEAR": "1986",
        "CREATOR_INSPIRATION_SOURCES": "Clowns and Bridge Trolls",
        "ENTITY_TRUE_NATURE_TYPE": "Trans-dimensional Alien",
        "ENTITY_ORIGIN_LOCATION_COSMIC": "The Macroverse (Void beyond dimensions)",
        "ENTITY_ARRIVAL_METHOD_EARTH": "Crash landing (Possibly via an asteroid)",
        "ENTITY_ARRIVAL_GEOLOGICAL_ERA": "Pre-human (Millions of years ago, possibly the dinosaur era)",
        "ENTITY_FIRST_RECORDED_WAKING_YEAR": "Circa 1715",
        "PRIMARY_TERROR_LOCATION_CITY": "Derry, Maine",
        "PRIMARY_TERROR_LOCATION_UNDERGROUND": "Sewer System/Underground Vaults",
        "FEEDING_CYCLE_DURATION_YEARS": "Approximately 27 years",
        "FEEDING_CYCLE_PRIMARY_PREY": "Children",
        "FEEDING_MOTIVATION_PSYCHOLOGICAL": "To 'salt the meat' (Fear makes the prey taste better)",
        "FEEDING_MOTIVATION_PHYSICAL": "Pure consumption/survival",
        "HIBERNATION_PERIOD_DURATION": "Around two and a half decades",
        "HIBERNATION_COMMENCEMENT_EVENT": "Defeat or extreme injury",
        "HIBERNATION_AWAKENING_SIGN": "Major town tragedy/violent event",
        "GENDER_PRIMARY_FORM_CLOWN": "Male (Referred to as 'he')",
        "GENDER_TRUE_FORM_NOVEL_IMPLICATION": "Female (Revealed to be pregnant with eggs)",
        "GENDER_OVERALL_BIOLOGICAL_STATUS": "Neither/Both (Asexual/Genderless entity)",
        "CLOWN_ALIAS_FULL": "Robert 'Bob' Gray",
        "CLOWN_SUIT_COLOR_NOVEL": "Silvery-white",
        "CLOWN_SUIT_DECORATION": "Large Orange Pom-poms/Buttons",
        "CLOWN_FEATURE_HAIR": "Red tufts (Around the sides of the head)",
        "CLOWN_FEATURE_EYE_DETAIL_FILM": "Subtly drifting/Lazy eye (Unsettling stare)",
        "CLOWN_FEATURE_GLOVES": "Big White Gloves",
        "CLOWN_FEATURE_NOVEL_APPEARANCE_INITIAL": "Friendly and approachable with big blue eyes",
        "CLOWN_FEATURE_FILM_APPEARANCE_INITIAL": "Menacing and disturbing from the start",
        "POWERS_PRIMARY_OFFENSE": "Shapeshifting (Into worst fears)",
        "POWERS_MENTAL_ABILITY_1": "Telepathy (Mind-reading/Detecting fears)",
        "POWERS_MENTAL_ABILITY_2": "Mind Control (On weak-minded adults/henchmen)",
        "POWERS_PHYSICAL_1": "Superhuman Strength",
        "POWERS_PHYSICAL_2": "Regeneration/Durability",
        "POWERS_PSYCHOLOGICAL_1": "Creating Illusions (Affecting all five senses)",
        "POWERS_PSYCHOLOGICAL_2": "Invisibility/Unnoticeable (To adults)",
        "POWERS_REALITY_WARPING": "Local Reality Manipulation (Within Derry)",
        "TRUE_FORM_MOST_PERCEIVABLE": "Giant Female Spider (The closest a human mind can comprehend)",
        "TRUE_FORM_ESSENCE": "The Deadlights (Swirling, chaotic orange lights)",
        "TRUE_FORM_EFFECT_ON_HUMAN_MIND": "Insanity or Catatonia (If stared into directly)",
        "DEFEAT_WEAKNESS_1_EMOTION": "Courage/Faith",
        "DEFEAT_WEAKNESS_2_CONDITION": "Group unity/Friendship/Love (The Losers' Club bond)",
        "DEFEAT_WEAKNESS_3_TACTIC": "Verbal ridicule/Non-belief (Calling out its tricks)",
        "DEFEAT_WEAKNESS_4_PHYSICAL_LAW": "Must obey the laws of the form it takes (e.g., a werewolf is vulnerable to silver)",
        "DEFEAT_METHOD_NOVEL": "The Ritual of Chüd (A battle of wills/imagination)",
        "PSYCHOLOGICAL_TACTIC_PRIMARY": "Weaponizing the victim's deepest fears",
        "PSYCHOLOGICAL_TACTIC_SECONDARY": "Taunting with dead relatives (e.g., Georgie's corpse)",
        "PREY_TARGET_GEORGIE_DENBROUGH_INJURY": "Arm bitten off",
        "PREY_TARGET_GEORGIE_DENBROUGH_LOCATION": "Storm Drain",
        "PREY_TARGET_EDDIE_KASPBRAK_FEAR_FORM": "Rotting Leper",
        "PREY_TARGET_STAN_URIS_FEAR_FORM_FILM": "Disturbing Painting Woman",
        "PREY_TARGET_BEN_HANSCOM_FEAR_FORM_FILM": "Charred/Headless Body",
        "PREY_TARGET_MIKE_HANLON_FEAR_FORM": "Reliving his parents' fire/death",
        "PREY_TARGET_BEVERLY_MARSH_FEAR_FORM_FILM": "Blood-spewing Bathroom Sink/Mrs. Kersh",
        "PREY_TARGET_RICHIE_TOZIER_FEAR_FORM_MINISERIES": "Werewolf",
        "HENCHMEN_PRIMARY_HUMAN": "Henry Bowers (Mind-controlled adult)",
        "RITUAL_CHUD_MEANING": "A metaphysical, psychic duel",
        "NOVEL_ANTAGONIST_ENEMY_COSMIC": "Maturin (The Cosmic Turtle)",
        "COSMIC_ENEMY_NATURE": "Force for good/Creator (Puked up our universe)",
        "COSMIC_ENTITY_CREATOR_SHARED": "Gan (Stephen King's ultimate deity)",
        "TERRITORIAL_LIMITATION": "Bound to the town of Derry, Maine",
        "NARCISSISM_WEAKNESS": "Arrogance/Underestimation of humans",
        "NOVEL_FORMS_TAKEN_CLASSIC_MONSTERS": "Mummy, Dracula, Werewolf, Frankenstein's Monster",
        "NOVEL_FORMS_TAKEN_LOCAL": "Lumberjack, various children and adults",
        "CINEMATIC_ADAPTATION_1_YEAR": "1990 (Miniseries)",
        "CINEMATIC_ADAPTATION_1_ACTOR": "Tim Curry",
        "CINEMATIC_ADAPTATION_2_YEAR": "2017 (Film)",
        "CINEMATIC_ADAPTATION_2_ACTOR": "Bill Skarsgård",
        "CINEMATIC_ADAPTATION_3_YEAR": "2019 (Film Sequel)",
        "CINEMATIC_ADAPTATION_PREQUEL_SERIES": "Welcome to Derry (2025)",
        "FILM_CLOWN_SUIT_AESTHETIC": "Victorian/Renaissance-style tattered suit",
        "FILM_PHYSICAL_BEHAVIOR_1": "Twitching/Jittering movements",
        "FILM_PHYSICAL_BEHAVIOR_2": "Contorted poses/Rapid changes",
        "FILM_VISUAL_SIGNATURE_1": "Red Balloon",
        "FILM_VISUAL_SIGNATURE_2": "The drain/sewer grate",
        "FILM_DIALOGUE_SIGNATURE_1": "'We all float down here'",
        "FILM_DIALOGUE_SIGNATURE_2": "'Hiya, Georgie!'",
        "ORIGIN_NOVEL_FIRST_EARTH_MEAL": "Possibly an early native American settlement",
        "ORIGIN_NOVEL_SECOND_EARTH_MEAL": "Disappearance of Derry Township settlers (1740s)",
        "ORIGIN_NOVEL_THIRD_EARTH_MEAL_SIGN": "Kitchener Ironworks explosion (1906)",
        "ASSOCIATED_TOWN_ILLNESS_THEORY": "The Derry Disease (A collective blindness to the horrors)",
        "FINAL_BATTLE_LOCATION_NOVEL": "The Drain/Sewers (Under the town)",
        "FINAL_TRUE_FORM_DESTRUCTION_METHOD_NOVEL": "Tearing out the heart (The physical organ in the spider body)",
        "NICHES_NOVEL_DETAIL_CLOWN_SOURCE": "Took the form and name of an actual traveling clown named Bob Gray",
        "NICHES_NOVEL_DETAIL_BLOOD_SPIT": "Can 'spit' the blood of his victims back at others",
        "NICHES_NOVEL_DETAIL_SPIDER_EGGS": "The pregnant spider form was laying eggs the Losers' Club had to destroy",
        "NICHES_NOVEL_DETAIL_HENRY_BOWERS_ESCAPE": "Released from the asylum by the ghost of Belch Huggins (An illusion by the entity)",
        "NICHES_OTHER_KING_UNIVERSE_REFERENCE_1": "Mentioned in 'Dreamcatcher' ('Pennywise Lives' graffiti)",
        "NICHES_OTHER_KING_UNIVERSE_REFERENCE_2": "The symbol on the Black Spot in 'It' is the same as the box in 'Under the Dome'",
        "NICHES_OTHER_KING_UNIVERSE_REFERENCE_3": "Mentioned in 'Insomnia' (Focuses on the 1950s events in Derry)",
        "NICHES_ADAPTATION_CHANGE_NOVEL_TIMELINE": "Non-linear in the book, linear in the films",
        "NICHES_ADAPTATION_CHANGE_RITUAL_CHUD": "Significantly simplified/altered in the films",
        "NICHES_FILM_DETAIL_DENTURES": "The sharp teeth are an illusion over a more monstrous maw",
        "NICHES_FILM_DETAIL_FOREHEAD_FLATTENED": "Part of the head is intentionally made bulbous and flat for an unnatural look",
        "NICHES_BEHAVIOR_OBSERVATION": "A predatory joy/sadistic glee in terrifying its victims",
        "NICHES_SOUNDS_ASSOCIATED": "Giggles, high-pitched laughter, and mocking voices",
        "NICHES_SKARSGARD_ACTOR_TRAIT": "Can physically move his lip up on one side to create an exaggerated snarl",
        "NICHES_KING_CREATOR_QUOTE": "Wanted a monster that was 'all the monsters in it'",
        "NICHES_CRITICAL_RECEPTION_STATUS": "Iconic villain/One of horror's scariest clowns",
        "NICHES_APARTMENT_VICTIM_DEATH_NOVEL": "Adrian Mellon (Killed by Its bully henchmen then consumed by It)",
        "NICHES_APARTMENT_VICTIM_DEATH_FILM_2": "Adrian Mellon (Attacked and thrown off a bridge by a manifestation of the entity)",
        "NICHES_LOSERS_CLUB_VOW": "Blood Oath (To return if the entity re-emerges)",
        "NICHES_LOSERS_CLUB_MEMORY_LOSS": "Fades upon leaving Derry's town limits",
        "NICHES_CLOWN_TRANSPORTATION_DEVICE": "A unicycle (Sometimes seen in the novel/miniseries)",
        "NICHES_SPIDER_FORM_SIZE": "Enormous/Building-sized",
        "NICHES_COSMIC_ENEMY_STATUS_NOVEL_LATER": "Reportedly choked on a galaxy or two (Bill is told this)",
        "NICHES_THEME_OF_THE_WORK": "The loss of childhood innocence and the power of memory/imagination",
        "NICHES_FIRST_VICTIM_GEORGIE_NOVEL_TIMELINE": "October 1957",
        "NICHES_FINAL_CONFRONTATION_ADULT_TIMELINE": "1985 (Novel)",
        "NICHES_FINAL_CONFRONTATION_ADULT_TIMELINE_FILM": "2016",
        "NICHES_ORIGINAL_CLOWN_COSTUME_TYPE": "Baggy, old-fashioned clown suit",
        "NICHES_FILM_COSTUME_PERIOD_INSPIRATION": "Medieval/Jester-like collar and cuffs",
        "NICHES_FILM_BODY_SHAPE_EFFECT": "Exaggerated large dome-like forehead and tight body suit",
        "NICHES_THEME_OF_THE_TOWN": "A place that is inherently evil/corrupted by the entity's presence",
        "NICHES_MAGICAL_SYMBOLISM_RITUAL": "The Smoke Hole (Where the Losers Club first perceive the ancient history)",
        "NICHES_ADULT_FEAR_EXPLOITED": "The fear of getting old and forgetting the past",
        "NICHES_SMELL_ASSOCIATED": "Decay, sulfur, and unwashed age (when in monster form)"
    },

    
    {
        "CHARACTER": "Dracula",
        "SOURCE": "Dracula (1897) by Bram Stoker",
        "IS_PART_OF_SERIES": "No (Original novel is standalone, but character is most portrayed in media)",
        "GENDER_DESCRIPTION": "Male (Undead Vampire Nobleman)",
        "IS_MALE": "Yes",
        "IS_HUMAN": "No (Undead/Vampire)",
        "IS_FICTIONAL": "Yes (Loosely inspired by Vlad the Impaler)",
        "PORTRAYED_BY": "Bela Lugosi (1931), Christopher Lee, Gary Oldman",
        "ORIGIN_LITERATURE": "Gothic Horror Novel (Epistolary format)",
        "FILM_SETTING_REGION": "Transylvania, Carpathian Mountains (Castle Dracula) & London, England",
        "SUPERNATURAL_NATURE": "Vampire (Acquired powers through dealings with the devil/black arts at Scholomance)",
        "PRIMARY_MOTIVATION": "To secure new blood sources in England and establish a dynasty of vampires.",
        "GOAL": "To spread his influence, feed, and live forever. To conquer the modern world with ancient evil.",
        "TRANSFORMATION": "Can shapeshift into a wolf, a bat, mist, or elemental dust.",
        "POWERS": ["Superhuman Strength", "Hypnosis & Telepathy", "Defiance of Gravity", "Control over animals"],
        "WEAKNESSES": ["Sunlight", "Sacred Objects (Crucifixes, garlic, holy water)", "The True Death (Beheading and staking the heart)", "Cannot cross running water", "Has no reflection"],
        "SIGNATURE_PHRASE": "Listen to them. The children of the night. What sweet music they make.",
        "NEMESIS": "Professor Abraham Van Helsing (Chief Antagonist)",
        "PROTÉGÉS": "The Three Brides of Dracula (Vampiresses in his castle)",
        "STATUS_AT_END_OF_FILM": "Destroyed/Killed by Jonathan Harker and Quincey Morris.",
        "IS_A_VILLAIN": "Yes (Archetypal Vampire/Antagonist)",
         "source_material": "Dracula (1897) by Bram Stoker",
  "identity_and_origin": {
    "gender": "Male",
    "status": "Undead Vampire",
    "title": "Count (Voivode)",
    "nationality": "Transylvanian (Szekler descent)",
    "historical_inspiration": "Likely based in part on Vlad III Dracula (Vlad the Impaler)",
    "approximate_age": "Over 400 years old (approx. 460 years)",
    "past_life_profession": "Soldier, Statesman, Alchemist, Voivode (warlord/prince)",
    "historical_claim": "Claims descent from Attila the Hun",
    "location_of_residence_start": "Castle Dracula, Carpathian Mountains, Transylvania",
    "location_of_residence_later": "Carfax Estate, near Purfleet, England",
    "native_language": "Unknown (Likely Romanian/Hungarian/Slavic)",
    "other_languages_spoken": "Excellent English (though initially only writes it), German, Latin"
  },
  "physical_appearance_initial": {
    "stature": "Tall",
    "build": "Lean, gaunt, spare, but possessing immense strength",
    "age_impression_initial": "Old man, appears elderly at first meeting",
    "hair_color_initial": "Grayish/Heavy gray, almost meeting over the nose (bushy)",
    "mustache_initial": "Long, heavy, white mustache",
    "eyebrows": "Very massive and bushy",
    "forehead": "Lofty, domed",
    "nose": "Aquiline (hooked), high bridge, peculiarly arched nostrils (thin)",
    "ears": "Pale and at the tops extremely pointed (subtle niche detail)",
    "face_pallor": "Extraordinary pallor (extreme paleness)",
    "lips": "Remarkably ruddy (red) which shows astonishing vitality",
    "teeth": "Peculiarly sharp white teeth, noticeably protruding over the lips (canine-like)",
    "expression_default": "Stoic, fixed, rather cruel-looking",
    "hands_description": "Rather coarse, broad, with squat fingers",
    "hands_niche_detail": "Hairs in the center of the palm (a traditional sign of depravity/werewolfism)",
    "nails": "Long, fine, and cut to a sharp point",
    "attire": "Clad in black from head to foot, without a single speck of color",
    "odor_niche": "Cold to the touch, and reportedly has a foul-smelling breath (implied by Harker’s reaction)"
  },
  "physical_appearance_later": {
    "age_impression_later": "Appears more youthful and vital after consuming blood in England",
    "hair_color_later": "Dark iron-gray",
    "face_vitality_later": "Possesses more vitality (less pallor)",
    "eyes_later": "Blazed with a ferocity/demoniac fury"
  },
  "personality_and_behavior": {
    "temperament_initial": "Charming, polite, highly courteous",
    "temperament_true": "Cunning, remorseless, predatory, fiercely cruel",
    "intellect": "Mighty brain, learning beyond compare, amassed wisdom over centuries",
    "emotional_state": "Knew no fear and no remorse (in his life), driven by insatiable bloodlust",
    "attitude_to_humanity": "Disdainful, views humans as prey or tools",
    "arrogance": "Highly arrogant, believing others 'shall yet be mine'",
    "willpower": "Possesses a strong, dominating will",
    "ambition": "To move from Transylvania to England and spread the undead curse",
    "planning_skill": "Metamorphic, demonstrates meticulous planning (e.g., real estate, 50 boxes of soil)",
    "manipulation_ability": "Master manipulator (e.g., using Renfield, controlling victims' minds)",
    "patience": "Extremely patient, having lived for centuries",
    "behavior_when_discovered": "Flash of rage or a horrible sort of snarl, quickly concealed by a cold stare",
    "behavior_on_walls": "Crawls down the castle wall like a lizard or spider (reptilian agility)",
    "behavior_social": "Initially very hospitable to guests like Harker, but this is a facade",
    "motivation_primary": "Bloodlust (the 'thirst') and a desire for domination/overthrow",
    "attitude_to_faith": "Uses his powers to ridicule religions and God's decisions",
    "attitude_to_women": "Views women as sources of blood and subjects for corruption/sexual perversion",
    "attitude_to_technology": "Represents the primitive past challenging the effectiveness of 'modernity'"
  },
  "supernatural_powers_and_abilities": {
    "superhuman_strength": "Strength equivalent to that of 20 strong men",
    "immortality": "Unable to die of senescence (aging)",
    "shapeshifting_form_wolf": "Can transform into a large wolf (as seen with the Demeter dog)",
    "shapeshifting_form_bat": "Can transform into a large bat",
    "shapeshifting_form_mist": "Can transform into a fog or mist (elemental dust)",
    "shapeshifting_size": "Can grow and become small",
    "teleportation": "Can 'vanish and reappear elsewhere at will' within limitations",
    "elemental_travel": "When moonlight is shining, he can travel as elemental dust within its rays",
    "passage_through_cracks": "Can pass through tiny cracks or crevices (hairbreadth space of a tomb door) in human form or as vapour",
    "wall_climbing": "Can climb vertical surfaces upside down in a reptilian manner (defies gravity)",
    "animal_control_wolves": "Can command wolves",
    "animal_control_bats": "Can command bats",
    "animal_control_rats": "Can command rats",
    "animal_control_other": "Can command owls, moths, foxes ('meaner things')",
    "weather_control_storm": "Can direct the elements, causing storms and harsh weather (e.g., Demeter's journey)",
    "weather_control_fog": "Can create fog or mist",
    "hypnotism": "Possesses powerful hypnotic and illusionary abilities",
    "telepathy": "Can communicate and manipulate minds (e.g., Renfield, Mina)",
    "necromancy_implied": "Aided by powers of necromancy and divination of the dead",
    "vampire_creation": "Ability to turn others into vampires by biting/infecting them with the vampiric disease",
    "undead_servants": "Those who die by his hand may reanimate and do his bidding",
    "knowledge_black_arts": "Studied black arts at the academy of Scholomance in the Carpathian Mountains",
    "knowledge_alchemy": "Deep knowledge of alchemy and magic"
  },
  "vampiric_limitations_and_weaknesses": {
    "reflection": "Does not cast a reflection from mirrors (no reflection)",
    "shadow": "Does not cast a shadow",
    "daylight_effect": "Powers are limited and cease at the coming of the day; he is rendered powerless by daylight (not killed)",
    "daylight_form_limitation": "Must remain in whatever form he is in when daylight comes until sunset",
    "need_for_invitation": "Cannot enter a victim's home/new space unless invited first (though can come as he pleases afterward)",
    "running_water_crossing": "Cannot cross running water at the slack or flood of the tide (must be carried or use a bridge)",
    "resting_requirement": "Must rest in his own native soil (50 boxes of earth from Transylvania)",
    "unhallowed_ground_access": "Can travel onto unhallowed ground (graves of suicides/victims)",
    "repulsion_garlic": "Repulsed and afflicted by garlic and garlic flowers",
    "repulsion_holy_items": "Repulsed and afflicted by sacred items and symbols (crucifixes, sacred wafers, communion bread)",
    "imprisonment_wild_rose": "Placing the branch of a wild rose upon the top of his coffin will render him unable to escape it",
    "defense_mountain_ash": "Mountain-ash is a form of protection from a vampire (effects unknown but traditional)",
    "vulnerability_physical": "Immune to conventional means of attack (blade goes through him as though air)",
    "vulnerability_killing_method_heart": "Can be killed by a stake driven through the heart",
    "vulnerability_killing_method_decapitation": "Can be killed by decapitation (often with a stake to the heart)",
    "vulnerability_killing_method_holy_bullet": "A sacred bullet fired into the coffin could kill him so that he remains 'true-dead'",
    "vulnerability_killing_circumstance": "Ultimately killed by a knife/Kukri cutting his throat and a knife/Kukri piercing his heart",
    "vulnerability_psychic_link": "A psychic connection with a victim (Mina) can be used by his enemies to track him"
  },
  "niche_lore_and_details": {
    "inspiration_etymology": "Dracula translates to 'son of the dragon' or 'devil' in Romanian",
    "early_name_concept": "Stoker's original name for the character was Count Wampyr",
    "castle_architectural_detail": "Castle Dracula rooms are absent of mirrors",
    "castle_location_detail": "Castle stands on the edge of an enormous cliff, overlooking the Carpathians",
    "female_vampires_possession": "Considers the three female vampires in his castle his property/possession ('belongs to me')",
    "relationship_with_minions": "Uses and then discards/kills those who do his bidding (e.g., Renfield, ship's crew)",
    "feeding_on_mina_niche": "Forces Mina Harker to drink his blood, cursing her to become a vampire after death unless he is destroyed",
    "initial_blood_source": "Drinks Jonathan Harker's blood on occasion for sustenance",
    "travel_vessel": "Travels to England aboard the ship *Demeter*",
    "weapon_of_death": "Killed by Quincey Morris's bowie knife/Kukri knife and Jonathan Harker's knife"
  }
    },


    {
        "CHARACTER": "Frankenstein",
        "SOURCE": "Frankenstein; or, The Modern Prometheus (1818) by Mary Shelley",
        "IS_PART_OF_SERIES": "No (Original novel is standalone, though pop culture made it a franchise)",
        "GENDER_DESCRIPTION": "Male (A newly created, sapient being)",
        "IS_MALE": "Yes",
        "IS_HUMAN": "No (Artificially created from collected human parts)",
        "IS_FICTIONAL": "Yes",
        "PORTRAYED_BY": "Boris Karloff (1931), Robert De Niro (1994), etc.",
        "ORIGIN_LITERATURE": "Gothic/Science Fiction Novel",
        "FILM_SETTING_REGION": "Ingolstadt, Bavaria (Creation); Geneva, Switzerland; The Arctic",
        "SUPERNATURAL_NATURE": "Alchemy/Galvanism/Applied Science",
        "PRIMARY_MOTIVATION": "Loneliness; seeking acceptance, love, and a female companion of its own kind after being abandoned by its creator.",
        "GOAL": "To compel his creator, Victor Frankenstein, to build a mate for him, or to destroy everything Victor loves.",
        "EDUCATIONAL_STATUS": "Highly intelligent and eloquent (Learns to read Milton, Plutarch, and Goethe)",
        "POWERS": ["Superhuman Strength & Endurance (8 feet tall)", "Exceptional Stamina", "High Intellect and Eloquence"],
        "WEAKNESSES": ["Emotional Rejection (His primary psychological weakness)", "Vulnerability to Normal Harm", "Isolation", "Fire (In many film adaptations)"],
        "SIGNATURE_PHRASE": "I ought to be thy Adam; but I am rather the fallen angel.",
        "CREATOR": "Victor Frankenstein (The real 'Frankenstein')",
        "VICTIMS": "William Frankenstein, Henry Clerval, Elizabeth Lavenza",
        "STATUS_AT_END_OF_FILM": "Mourns the death of Victor Frankenstein, vowing to burn himself on a pyre, and then departs into the Arctic.",
        "IS_A_VILLAIN": "Yes (Villain by consequence/abandonment; Sympathetic Antagonist)",
        "origin": "Mary Shelley's novel 'Frankenstein; or, The Modern Prometheus' (1818)",
  "designation": "Nameless, often referred to as 'Creature,' 'Monster,' 'Demon,' 'Fiend,' 'Wretch,' 'Adam of my labours'",
  "creator": {
    "name": "Victor Frankenstein",
    "relationshipType": "Father/Creator (abandoning)",
    "primaryGoal": "Revenge against his creator for abandonment"
  },
  "physicalAttributes": {
    "height": "Approximately 8 feet (2.4 meters)",
    "complexion": "Dull yellow skin, scarcely covering the underlying muscles and arteries",
    "eyes": "Watery, of a dun-white color, set in corresponding sockets",
    "hair": "Lustrous black, and flowing",
    "teeth": "Pearly whiteness (a horrible contrast to the rest of his features)",
    "physique": "Superhumanly strong and agile, large and grotesque frame",
    "mobility": "Remarkably swift and capable of navigating rugged terrain (Alps, Arctic)",
    "texture": "Skin is stretched tightly over the mechanical workings beneath",
    "face": "Shriveled with a horrid contrast of features",
    "movementStyle": "Convulsive and agitated upon initial reanimation, later becomes swift and coordinated"
  },
  "creationDetails": {
    "method": "Assembled from parts of disinterred bodies and reanimated via an ambiguous scientific process (possibly galvanism/electricity)",
    "location": "A solitary apartment in Ingolstadt",
    "dateOfBirth": "A dreary night in late autumn",
    "reactionOfCreator": "Immediate horror, disgust, and flight (abandonment)",
    "materials": "Body parts gathered from charnel houses and dissecting rooms"
  },
  "intellectualProfile": {
    "learningCapacity": "Extreme and rapid",
    "languageAcquisition": "Learned to speak, read, and write by observing the De Lacey family through a hovel window",
    "languagesKnown": ["German", "French", "English (fluently)"],
    "literaryInfluences": [
      {"title": "Paradise Lost", "impact": "Learned about creation, sin, and felt kinship with Satan"},
      {"title": "Plutarch's Lives", "impact": "Gained a sense of history, heroism, and public virtue"},
      {"title": "The Sorrows of Young Werther", "impact": "Learned about passion, despair, and suicide"},
      {"title": "Victor's Journal", "impact": "Discovered the details of his own hideous creation and abandonment"}
    ],
    "selfEducation": "Entirely self-taught in language, history, and social dynamics through observation",
    "eloquence": "Highly articulate, persuasive, and verbose in speech (contrary to popular culture)",
    "reasoning": "Capable of complex moral and philosophical arguments"
  },
  "psychologicalProfile": {
    "initialState": "Innocent, sensitive, child-like, and benevolent (a 'noble savage' archetype)",
    "dominantNeeds": ["Companionship", "Acceptance", "Love", "Empathy"],
    "coreTrauma": "Immediate and total abandonment by his creator, followed by universal rejection by humankind",
    "emotionalSpectrum": ["Deep loneliness", "Intense despair", "Fierce rage", "Affection (for De Laceys)", "Guilt (post-murders)", "Mourning (for Victor)"],
    "moralDevelopment": "Starts with inherent goodness but is corrupted by continuous social injustice and maltreatment",
    "motivationForMurder": "Vengeance against Victor, driven by profound emotional pain and rejected need for a companion",
    "selfPerception": "Views himself as a 'wretch,' 'demon,' and 'fallen angel' who is cut off from a common nature",
    "copingMechanism": "Isolation, observation, and eventually, destructive rage",
    "finalIntention": "Self-immolation at the North Pole to end his existence and prevent further harm",
    "existentialDilemma": "An unloved, solitary 'species' with no place in the world"
  },
  "behavioralTraits": {
    "earlyActsOfKindness": [
      "Gathering firewood for the De Lacey family anonymously",
      "Clearing snow from their path",
      "Avoiding humans to prevent terror"
    ],
    "firstEncounter": "Attacked and driven away from a shepherd's hut after being seen",
    "diet": "Vegetarian (eats 'acorns and berries'), stating 'My food is not that of man'",
    "travels": "Extensive, across Europe (Germany, Switzerland, England, Scotland) and finally to the Arctic",
    "murderVictims": [
      {"name": "William Frankenstein", "motive": "To inflict emotional pain on Victor"},
      {"name": "Henry Clerval", "motive": "Revenge for Victor destroying the female companion"},
      {"name": "Elizabeth Lavenza", "motive": "Final act of retribution on Victor's wedding night"}
    ],
    "manipulation": "Frames Justine Moritz for William's murder",
    "requestToVictor": "The creation of a female companion to alleviate his solitude",
    "interactionStyle": "Initially humble and pleading, later demanding and threatening",
    "reactionToDeath": "Mourns over Victor's corpse, expressing guilt and despair"
  },
  "socialStatus": {
    "gender": "Male-presenting (referred to as 'he,' 'him')",
    "socialClass": "None (an outcast and singular being)",
    "nationality": "None (created in Ingolstadt, abandoned in Geneva)",
    "maritalStatus": "Single (companion denied)",
    "relationshipWithFire": "Uses it for warmth and cooking; plans to use it for his own funeral pyre (not afraid, contrary to pop culture)"
  },
  "nicheAndContextualDetails": {
    "ageAtStoryStart": "Newborn (mentally/physically)",
    "timeElapsedDuringLearning": "Learned language, reading, and history in approximately 11 months",
    "narrativeFunction": "Functions as a tragic villain and a sympathetic secondary narrator (in Chapters 11-17)",
    "literaryArchetype": ["Prometheus's creation", "Noble Savage", "Fallen Angel"],
    "connectionToRomanticism": "Embodies the Romantic focus on sublime nature, emotional intensity, and the solitary individual",
    "critiqueOfEnlightenment": "His existence critiques Victor's unrestrained scientific ambition and rationalism without responsibility",
    "clothing": "Dresses himself in dark garments soon after creation",
    "religiousView": "Questions his existence and status relative to 'Adam' and 'Satan'",
    "symbolism": "Represents the monstrous consequences of parental/creator neglect and societal prejudice",
    "perceptionByHumans": "Universally perceived as hideous and terrifying upon sight",
    "influenceOnPopCulture": "The character (often misidentified as 'Frankenstein') is a staple of horror, science fiction, and cinema"
  }

    }
]

def populate_mongodb():
    """Connects to MongoDB and inserts the full character list, clearing previous data."""
    try:
        client = MongoClient(MONGO_URI) #connect to db
        print(f"📡 Connecting to MongoDB...")

        db = client[DB_NAME] #access db n collection
        character_collection = db[COLLECTION_NAME]

        existing_count = character_collection.count_documents({})
        if existing_count > 0:
            print(f"⚠️  Found {existing_count} existing documents in {DB_NAME}.{COLLECTION_NAME}")
            user_input = input("Do you want to delete existing data and insert fresh? (yes/no): ").lower()
            if user_input == 'yes':
                character_collection.delete_many({})
                print("🗑️  Cleared existing data.")
            else:
                print("keep existing data n adding new characters!")       
   
        #remove any id field id present
        for char in initial_characters:
            if 'id' in char:
                char.pop('id')

        result = character_collection.insert_many(initial_characters)
        print(f"✅ Success! Inserted {len(result.inserted_ids)} characters into {DB_NAME}.{COLLECTION_NAME}.")

        total_count = character_collection.count_documents({})
        print(f"📊 Total characters in collection: {total_count}")
        
        client.close()
        print("db connection closed")

    except Exception as e:
        print(f" Connection/Insertion Failed: {e}")

if __name__ == "__main__":
    populate_mongodb()
